eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/server/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      #Gateway默认转发是全路径的，设置StripPrefix=1表示从二级url路径转发，
      #即http://localhost:port/activity/test将会转发到http://{activity}/test
      - id:  api-base
      # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://freedom-base
        predicates:
        # 重点！转发该路径！,/api-base/**,
        - Path=/api-base/**
        # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
        #而不是我们期望的去掉userapi，只保留**部分
        filters:
        - StripPrefix=1
#        - name:
#          args:
#            name: hystrixCommand
#            fallBackUrl: forward: /hystrixTimeout



security:
  oauth2:
    client:
      access-token-uri: http://localhost:9997/oauth/token
      user-authorization-uri: http://localhost:9997/oauth/authorize
      client-id: app
      grant-type: password
      client-secret: 123456
    resource:
      user-info-uri: http://localhost:9997/user
      prefer-token-info: false
